export const filterActions = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS'
};
