export const filterActions = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
export const filterActionsDiago = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
export const filterActionsFollowUp = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
export const bulkFilterActions = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
export const bulkFilterActionsDiago = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
export const bulkFilterActionsFollowUp = {
  STAGES: 'STAGES',
  REPRESENTATIVE: 'REPRESENTATIVE',
  PHONE: 'PHONE',
  ADMISSIONTYPE: 'ADMISSIONTYPE',
  DIAGNOSTICSTYPE: 'DIAGNOSTICSTYPE',
  DATERANGE: 'DATERANGE',
  RESULTS: 'RESULTS',
  STATUS: 'STATUS',
  FOLLOWUP: 'FOLLOWUP',
  PAIRTYPE: 'PAIRTYPE'
};
