export enum Roles {
  SUPPORT = 'SUPPORT',
  ADMIN = 'ADMIN',
  REPRESENTATIVE = 'REPRESENTATIVE',
  REPRESENTATIVEONE = 'REPRESENTATIVEONE',
  REPRESENTATIVETWO = 'REPRESENTATIVETWO',
  REPRESENTATIVETHREE = 'REPRESENTATIVETHREE',
  REPRESENTATIVEFOUR = 'REPRESENTATIVEFOUR',
  REPRESENTATIVEFIVE = 'REPRESENTATIVEFIVE',
  PHARMACY = 'PHARMACY',
  AUDIT="AUDIT",
}
  